Hamburger Sitesi/HamburgerSitesi.WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace HamburgerSitesi.WebUI.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class DashboardController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Hamburger Sitesi/HamburgerSitesi.WebUI/Controllers/AuthController.cs
using HamburgerSitesi.Business.Dtos;
using HamburgerSitesi.Business.Services;
using HamburgerSitesi.WebUI.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace HamburgerSitesi.WebUI.Controllers
{
	public class AuthController : Controller
	{
		private readonly IUserService _userService;
		public AuthController(IUserService userService)
		{
			_userService = userService;
		}
		[HttpGet]
		[Route("KayitOl")]
		public IActionResult Register()
		{
			return View();
		}
		[HttpPost]
		[Route("KayitOl")]
		public IActionResult Register(RegisterViewModel formData)
		{
			if (!ModelState.IsValid)
			{
				return View(formData);
			}
			var addUserDto = new AddUserDto()
			{
				Email = formData.Email.Trim(),
				FirstName = formData.FirstName.Trim(),
				LastName = formData.LastName.Trim(),
				Password = formData.Password.Trim(),
			};
			var result = _userService.AddUser(addUserDto);
			if (result.IsSucceed)
			{
				return RedirectToAction("Index", "Home");

			}
			else
			{
				ViewBag.ErrorMessage = result.Message;
				return View(formData);
			}
			return RedirectToAction("Index", "Home");


		}
		public async Task<IActionResult> login(LoginViewModel formData)
		{
			if (!ModelState.IsValid)
			{
				return RedirectToAction("Index", "Home");
			}
			var loginDto = new LoginDto
			{
				Email = formData.Email,
				Password = formData.Password
			};
			var userInfo = _userService.LoginUser(loginDto);
			if (userInfo is null)
			{
				return RedirectToAction("Index", "Home");
			}
			var claims = new List<Claim>();

			claims.Add(new Claim("id", userInfo.Id.ToString()));
			claims.Add(new Claim("email", userInfo.Email));
			claims.Add(new Claim("firstName", userInfo.FirstName));
			claims.Add(new Claim("lastName", userInfo.LastName));
			claims.Add(new Claim("userType", userInfo.UserType.ToString()));
			claims.Add(new Claim(ClaimTypes.Role, userInfo.UserType.ToString()));
			var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
			var autProperties = new AuthenticationProperties
			{
				AllowRefresh = true,
				ExpiresUtc = new DateTimeOffset(DateTime.Now.AddHours(48))
			};
			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity), autProperties);




			return RedirectToAction("Index", "Home");
		}
		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync();

			return RedirectToAction("Index", "Home");
		}

	}

}

Hamburger Sitesi/HamburgerSitesi.WebUI/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace HamburgerSitesi.WebUI.Controllers
{
    public class MenuController : Controller
    {
		
		public IActionResult Index()
        {
			return View();
        }
		
        public IActionResult Menu()
        {
			return View();
        }

    }
}

Hamburger Sitesi/HamburgerSitesi.WebUI/Controllers/OdemeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HamburgerSitesi.WebUI.Controllers
{
	public class OdemeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Odeme()
		{
			return View();
		}
	}
}

Hamburger Sitesi/HamburgerSitesi.WebUI/Views/Shared/_Layout.cshtml
@using HamburgerSitesi.WebUI.Extensions;
<html>
<head>
	<title>Hamburger Proje Sitesi</title>

	<meta name="description" content="Yzl8146 Sınıfı için yapılan MVC web projesi">
	<meta name="keywords" content="HTML, CSS, JavaScript, Jquery, MVC, .Net, Asp.Net, BilgeAdam">
	<meta name="author" content="Bahriye Başer">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<style>
	label.required:after {
		content: "*\00a0";
		color: red;
		margin-left: 2px;
	}
</style>

<header class="p-3 text-bg-dark">
	<div class="container">
		<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
			<a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
				<svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
			</a>

			<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
				
				
				<li><a asp-controller ="Home" asp-action="Index" class="nav-link px-2 text-white">ANASAYFA</a></li>
				<li><a href="#" class="nav-link px-2 text-white">KURUMSAL</a></li>
				<li><a asp-controller="Menu" asp-action="Menu" class="nav-link px-2 text-white">MENÜ</a></li>
				<li><a href="#" class="nav-link px-2 text-white">GALERİ</a></li>
				<li><a href="#" class="nav-link px-2 text-white">ŞUBELER</a></li>
			</ul>

			<div class="text-end">
				<a asp-controller="Odeme" asp-action="Odeme" class="btn btn-info">ONLİNE SİPARİŞ</a>


				<div class="d-none" id="login">
					<partial name="_LoginPartial" model="new LoginViewModel()">
				</div>
				@if (!User.IsLogged())
					
				{
					<div id="welcome">
						<partial name="_WelcomePartial">
					</div>

				}
				else
				{
					var firstName = User.GetUserFirstName();
					var lastName = User.GetUserLastName();
					<div class="d-flex">

						<div class="mt-2">
							HOŞGELDİN @firstName @lastName
						</div>
						@if (User.IsAdmin())
						{
							<div class="ms-3">
								<a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="btn btn-danger">Yönetim Paneli</a>
							</div>
						}
						<a asp-controller="Auth" asp-action="Logout" class="btn btn-outline-warning ms-3">Çıkış Yap</a>


					</div>
				<div class="alert alert-danger text-center">
					Oturum açıldı
				</div>
				}

			</div>
		</div>
	</div>
</header>
<body class="d-flex flex-column min-vh-100">
	<div class="container">
		@RenderBody()
	</div>
	<footer class="py-3 my-4">
		<ul class="nav justify-content-center border-bottom pb-3 mb-3">
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">ANASAYFA</a></li>
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">KURUMSAL</a></li>
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">MENÜ</a></li>
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">GALERİ</a></li>
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">ŞUBELER</a></li>

		</ul>
		<p class="text-center text-body-secondary">© 2023 Çankaya/ANKARA</p>
	</footer>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script>
		$('#btnGirisYap').click(function () {
			$('#login').removeClass('d-none');
			$('#welcome').addClass('d-none');
		})
		$('#btnIptal').click(function () {
			$('#login').addClass('d-none');
			$('#welcome').removeClass('d-none');
		})
	</script>
</body>
</html>

Hamburger Sitesi/HamburgerSitesi.WebUI/Views/Shared/_WelcomePartial.cshtml
<div class="text-end">
    <button id="btnGirisYap" type="button" class="btn btn-outline-light me-2">Giriş Yap</button>
    <a asp-controller="Auth" asp-action="Register" class="btn btn-warning">Kayıt Ol</a>
</div>